name: Build Portfolio

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Stage changes
      run: |
        git add .

    - name: Commit changes
      run: |
        git commit -m "Modify portfolio"

    - name: Push changes
      run: |
        git push
